// Generates supabase/seed.sql for the global starter decks.
// Faithfully mirrors backend/app/db.py _seed_database: process SEED_DECKS first,
// then the deck_expansions*.json files (sorted by filename), merging by slug and
// de-duplicating cards by (spanish, english) case-insensitively (first wins).
//
// Run: node supabase/scripts/generate_seed.cjs
const fs = require('fs');
const path = require('path');
const { optText, normCard, pairKey } = require('./lib/cards.cjs');
// The 3 hand-authored starter decks live in lib/seed_decks.cjs (shared with the
// AI generator). Card normalization helpers live in lib/cards.cjs.
const SEED_DECKS = require('./lib/seed_decks.cjs');

const DATA_DIR = path.resolve(__dirname, '../seed_data');
const OUT = path.resolve(__dirname, '../seed.sql');

// Build the ordered source list: SEED_DECKS, then expansion files sorted by name.
const sources = [...SEED_DECKS];
const files = fs.readdirSync(DATA_DIR).filter(f => /^deck_expansions.*\.json$/.test(f)).sort();
for (const f of files) {
  const payload = JSON.parse(fs.readFileSync(path.join(DATA_DIR, f), 'utf8'));
  if (!Array.isArray(payload)) throw new Error(f + ' must be a list');
  sources.push(...payload);
}

// Merge by slug, de-dupe cards by (spanish, english).
const decks = new Map(); // slug -> {slug,title,description,language_from,language_to,cards:[],seen:Set}
for (const src of sources) {
  const slug = optText(src.slug);
  const title = optText(src.title);
  const description = optText(src.description);
  if (!slug || !title || !description) throw new Error('deck missing slug/title/description: ' + slug);
  if (!Array.isArray(src.cards) || src.cards.length === 0) throw new Error('deck has no cards: ' + slug);
  let entry = decks.get(slug);
  if (!entry) {
    entry = { slug, title, description, language_from: optText(src.language_from) || 'es', language_to: optText(src.language_to) || 'en', cards: [], seen: new Set() };
    decks.set(slug, entry);
  }
  for (const c of src.cards) {
    const nc = normCard(c, entry.title);
    const key = pairKey(nc.spanish_text, nc.english_text);
    if (entry.seen.has(key)) continue;
    entry.seen.add(key);
    entry.cards.push(nc);
  }
}

const sq = (s) => s === null ? 'null' : "'" + String(s).replace(/'/g, "''") + "'";
const jsonLit = (obj) => "'" + JSON.stringify(obj).replace(/'/g, "''") + "'";

let sql = `-- AUTO-GENERATED by supabase/scripts/generate_seed.cjs — do not edit by hand.\n`;
sql += `-- Global starter decks (user_id IS NULL). Idempotent: safe to re-run.\n\n`;
sql += `begin;\n\n`;

let totalCards = 0;
for (const deck of decks.values()) {
  totalCards += deck.cards.length;
  sql += `-- ${deck.slug} (${deck.cards.length} cards)\n`;
  sql += `insert into public.decks (slug, title, description, language_from, language_to)\n`;
  sql += `values (${sq(deck.slug)}, ${sq(deck.title)}, ${sq(deck.description)}, ${sq(deck.language_from)}, ${sq(deck.language_to)})\n`;
  sql += `on conflict (slug) do nothing;\n\n`;

  const cardsJson = deck.cards.map(c => ({
    spanish_text: c.spanish_text,
    english_text: c.english_text,
    section_name: c.section_name,
    part_of_speech: c.part_of_speech,
    definition_en: c.definition_en,
    main_translations_es: c.main_translations_es,
    collocations: c.collocations,
    example_sentence: c.example_sentence,
    example_es: c.example_es,
    example_en: c.example_en,
  }));

  sql += `insert into public.cards (deck_id, spanish_text, english_text, is_enabled, generation_phase, generation_metadata, section_name, part_of_speech, definition_en, main_translations_es, collocations, example_sentence, example_es, example_en)\n`;
  sql += `select dk.id, x.spanish_text, x.english_text, true, 'refined', '{}'::jsonb, x.section_name, x.part_of_speech, x.definition_en,\n`;
  sql += `       coalesce(x.main_translations_es, '[]'::jsonb), coalesce(x.collocations, '[]'::jsonb), x.example_sentence, x.example_es, x.example_en\n`;
  sql += `from (select id from public.decks where slug = ${sq(deck.slug)}) dk\n`;
  sql += `cross join jsonb_to_recordset(${jsonLit(cardsJson)}::jsonb) as x(\n`;
  sql += `  spanish_text text, english_text text, section_name text, part_of_speech text, definition_en text,\n`;
  sql += `  main_translations_es jsonb, collocations jsonb, example_sentence text, example_es text, example_en text\n`;
  sql += `)\n`;
  sql += `where not exists (\n`;
  sql += `  select 1 from public.cards c2\n`;
  sql += `  where c2.deck_id = dk.id\n`;
  sql += `    and lower(c2.spanish_text) = lower(x.spanish_text)\n`;
  sql += `    and lower(c2.english_text) = lower(x.english_text)\n`;
  sql += `);\n\n`;
}

sql += `commit;\n`;

fs.writeFileSync(OUT, sql, 'utf8');
console.log(`Wrote ${OUT}`);
console.log(`Decks: ${decks.size}, total cards: ${totalCards}, file size: ${(sql.length / 1024).toFixed(1)} KB`);
for (const deck of decks.values()) console.log(`  ${deck.slug}: ${deck.cards.length}`);
